### ISSUE TITLE
question on team-provider-info

### ISSUE THREAD

**Issue by hyochan** [dabit3/amplify-auth-demo#1]
Hi! @dabit3. Thank you for all your awesome tutorials for those who are willing to try out serverless framework amplify!

Shouldn't [team-provider-info.json](https://github.com/dabit3/amplify-auth-demo/blob/master/amplify/team-provider-info.json) be included in `.gitignore`?

This file contains some credentials but this isn't included in `.gitignore` when initiating an amplify project.

**Comment by dabit3** [comment]
Hi @hyochan , yes! This should definitely not be in GitHub. Thanks for flagging this, I'll be removing this now.
